name: PR-workflow

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        uses: azohra/shell-linter@latest
 
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: ./tests/test_runner
        shell: bash
    needs: lint 